### ISSUE TITLE
Region screenshots cropping on all black backgrounds

### ISSUE THREAD

**Issue by jmalexan** [Gustash/Hyprshot#15]
When I take a region screenshot of some kind of image or text on an all black background (examples: my default terminal emulator theme, some of the new [Apple marketing pages](https://www.apple.com/iphone-15-pro/)), the screenshot comes out as cropped down as close as possible to the content on the all black background.  This kind of functionality actually could be pretty cool as an intended feature, maybe through an argument (and maybe another argument to customize how much padding is around the content being cropped to), but it should definitely be able to be turned off to give screenshots exactly as selected with the region selector.

Command I'm using to run: `hyprshot -m region --clipboard-only`

**Comment by Ghosthree3** [comment]
Experiencing the same issue but with a white background. Trying to screenshot some text on a page and the image that comes out is cropped perfectly around the text/paragraph with no border at all, even when i intentionally make the border area quite large.
This could be useful, but looks pretty awful when viewed on any non matching background canvas later.

**Comment by Gustash** [comment]
I tried it out myself with the examples provided and the PR fixed the issues. Please re-open if you see that this still happens.
