### ISSUE TITLE
Sometimes doesn't initiate on vertical monitor

### ISSUE THREAD

**Issue by EysseW** [Gustash/Hyprshot#20]
Sometimes doesn't make a screenshot if I try it on my vertical monitor. I get the selection box, but it doesn't copy the screenshot to the clipboard, it doesn't give a notification and it also doesn't the image to the specified output. It seems to fail only when I make the screenshot slowly. If I do it in a quick swipe, if work everytime (from my testing). 

Running latest version of Hyprland on Archlinux

**Comment by EysseW** [comment]
Yes, the output is:
`Saving in: /home/rat/Pictures/Screenshots//2023-10-07-000136_hyprshot.png
Geometry: 451,1581 423x257
Crop: 451,1581 423x-131
supplied geometry did not intersect with any outputs`

**Comment by Gustash** [comment]
> Yes, the output is:
> 
> ```Saving in: /home/rat/Pictures/Screenshots//2023-10-07-000136_hyprshot.png
> 
> Geometry: 451,1581 423x257
> 
> Crop: 451,1581 423x-131
> 
> supplied geometry did not intersect with any outputs```

Can you also attach the output of `hyprctl monitors`?

**Comment by katawful** [comment]
I have this issue as well, my vertical monitor is set up so that the top and bottom do not line up with the primary display (both 1080p displays, primary is at 420px y)

`hyprshot -d -m region` in affected region:

```
Saving in: /home/xxx/Pictures/2023-10-27-194528_hyprshot.png
Geometry: 3971,1675 442x245
Crop: 3971,1675 442x-175
supplied geometry did not intersect with any outputs
```

`hyprctl monitors` (HDMI-A-2 is vertical monitor):
```
Monitor HDMI-A-1 (ID 1):
	1920x1080@60.00000 at 0x420
	description: Acer Technologies GN246HL LW3AA0018532 (HDMI-A-1)
	make: Acer Technologies
	model: GN246HL
	serial: LW3AA0018532
	active workspace: -1339 (secondary-1)
	special workspace: 0 ()
	reserved: 0 28 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 0):
	1920x1080@60.00000 at 1920x420
	description: Dell Inc. D3218HN X9R5K8961XHE (DP-2 via HDMI)
	make: Dell Inc.
	model: D3218HN
	serial: X9R5K8961XHE
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 28
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor HDMI-A-2 (ID 2):
	1920x1080@60.00000 at 3840x0
	description: LG Electronics E2351 203RKKS0R581 (HDMI-A-2)
	make: LG Electronics
	model: E2351
	serial: 203RKKS0R581
	active workspace: -1338 (social-1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: 0


```

**Comment by olivier-hnry** [comment]
I happen to experience a similar issue.
Apparently, the part of my monitor that has a negative coordinate is cropped.
```
Saving in: /home/olivier/Pictures/2023-11-03-234314_hyprshot.png
Monitors: [{
    "id": 1,
    "name": "DP-1",
    "description": "Iiyama North America PL3270Q 1155101521058 (DP-1 via HDMI)",
    "make": "Iiyama North America",
    "model": "PL3270Q",
    "serial": "1155101521058",
    "width": 2560,
    "height": 1440,
    "refreshRate": 59.95100,
    "x": -100,
    "y": 0,
    "activeWorkspace": {
        "id": 7,
        "name": "7"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 24, 0, 0],
    "scale": 1.00,
    "transform": 0,
    "focused": true,
    "dpmsStatus": true,
    "vrr": false
}]
Active workspace: {
    "id": 7,
    "name": "7",
    "monitor": "DP-1",
    "windows": 1,
    "hasfullscreen": false,
    "lastwindow": "0x55a93032e120",
    "lastwindowtitle": "hyprshot -c -d -m output"
}
Current output: {
  "id": 1,
  "name": "DP-1",
  "description": "Iiyama North America PL3270Q 1155101521058 (DP-1 via HDMI)",
  "make": "Iiyama North America",
  "model": "PL3270Q",
  "serial": "1155101521058",
  "width": 2560,
  "height": 1440,
  "refreshRate": 59.95100,
  "x": -100,
  "y": 0,
  "activeWorkspace": {
    "id": 7,
    "name": "7"
  },
  "specialWorkspace": {
    "id": 0,
    "name": ""
  },
  "reserved": [
    0,
    24,
    0,
    0
  ],
  "scale": 1.00,
  "transform": 0,
  "focused": true,
  "dpmsStatus": true,
  "vrr": false
}
Geometry: -100,0 2560x1440
Crop: 0,0 2460x1440
```

![2023-11-03-234314_hyprshot](https://github.com/Gustash/Hyprshot/assets/75161856/4428815c-ed7c-499f-92c1-850c23adf1fd)


As you can see, the 100 leftmost pixel columns of my screen have been removed. If I put my monitor at `-3000` I get
```
Geometry: -3000,0 2560x1440
Crop: 0,0 -440x1440
supplied geometry did not intersect with any outputs
```
(-440 being -3000+2560) so I guess this is a misbehavior of the cropping process when it encounters negative coordinates.

My workaround is to translate my monitors so all the pixels have positive coordinates.

**Comment by Gustash** [comment]
Yes, setting negative coordinates is not advised. You should work off of the top-most and left-most monitors. Either way, it is possibly related but that specific scenario will not be tested or supported
