### ISSUE TITLE
when using --current with monitor scale set to 2, output image size is wrong

### ISSUE THREAD

**Issue by lemmerk** [Gustash/Hyprshot#22]
my desktop has a resolution of 3480x2160 and i have the following line in my config:
`monitor=,preferred,auto,2`

running the following:
```
$ hyprshot --mode=output --current --filename=current.png
$ hyprshot --mode=output --filename=not-current.png

$ identify current.png not-current.png
current.png PNG 7680x4320 7680x4320+0+0 8-bit sRGB 565255B 0.000u 0:00.000
not-current.png PNG 3840x2160 3840x2160+0+0 8-bit sRGB 411421B 0.000u 0:00.000
```
current.png shows the correct screenshot but it is in the top left quarter with the rest of the png being transparent.

---

as soon as i change the configuration line to use scale 1:
`monitor=,preferred,auto,1`

i get the following:

```
$ hyprshot --mode=output --current --filename=current-scale-1.png

$ identify current-scale-1.png
current-scale-1.png PNG 3840x2160 3840x2160+0+0 8-bit sRGB 179050B 0.000u 0:00.000
```
and current-scale-1.png shows the screenshot filling the entire image as expected.

**Comment by Gustash** [comment]
We need to take scale into account, I missed that detail since I use 1x scale on my monitors. I'll take a look later today, thanks for the report
