### ISSUE TITLE
When using -m output, unfocus the current window grabbing the cursor, or automatically execute the screenshot on currently focused output without the need to click

### ISSUE THREAD

**Issue by DaneelaArt** [Gustash/Hyprshot#29]

**Comment by Gustash** [comment]
You can already do this by using `-m output -m active`

**Comment by Gustash** [comment]
You can already do this by using `-m output -m active`

**Comment by DaneelaArt** [comment]
that did not seem to work, i have tried:
hyprshot -m output -m active
hyprshot -m output -m DP-2
hyprshot -m output -m 0
all of these produced no notification, nothing on my clipboard or in the pictures folder

**Comment by Gustash** [comment]
Are you using the latest commit? I haven't made a new release, so in the last release there should be a `-c` flag instead. Use the `--help` flag.
