### ISSUE TITLE
Wrong crop in dual-monitor setup

### ISSUE THREAD

**Issue by JcBernack** [Gustash/Hyprshot#32]
I have a dual-monitor setup:
- primary: 2560x1440 at 1200,200
- secondary: 1200x1920 at 0,0 (to the left of the primary and rotated to portrait 90°)

Both slurp and grim function correctly but using Hyprshot the image is cropped to the wrong dimensions.

Slurp output when selecting displays:
```
> slurp -o
0,0 1200x1920
> slurp -o
1200,200 2560x1440
```
Taking screenshots with grim using `grim -o DP-2` or `grim -o DP-3` also works correctly.

With Hyprshot I get the correct result on the primary display:
```
> hyprshot --clipboard-only -m output -d
Geometry: 1200,200 2560x1440
Crop: 1200,200 2560x1440
```

On the secondary this happens:
```
> hyprshot --clipboard-only -m output -d
Geometry: 0,0 1200x1920
Crop: 0,0 1200x1640
```

Somehow a screenshot of the secondary display is cropped to the height of the primary display plus the 200px offset.
If I remove the offset, i.e. move primary display to 1200,0 the screenshot is cropped to 1440.

**Comment by ProMix0** [comment]
There are some problems with geometry trim - it doesn't use monitor transform in calculations

But I have a question about trim() method - @Gustash, do we really need trim logic? Without it all works

**Comment by Gustash** [comment]
> There are some problems with geometry trim - it doesn't use monitor transform in calculations
> 
> 
> 
> But I have a question about trim() method - @Gustash, do we really need trim logic? Without it all works

It's for floating window selection, in case your window is slightly off screen. Otherwise you'd get black rectangles in the areas of the window that are off screen. 

We probably need to revise the trimming logic a bit tho, I didn't see these edge cases because I use a 1x DPI on both my monitors and have a regular side-by-side setup
