### ISSUE TITLE
Only top of the image is grabbed (bottom is cropped out)

### ISSUE THREAD

**Issue by Memoframe** [Gustash/Hyprshot#41]
Arch, system is updated.
hyprland 0.39.1-5
hyprshot 1.2.3-1
grim 1.4.1-1
grim+slurp give same result, so maybe it's on my end? but what should I do then?

Example:
![image](https://github.com/Gustash/Hyprshot/assets/15750345/fd839177-e831-4039-b826-370fe14a217c)

**Comment by lividhen** [comment]
Same thing happens with watershot 🤔

**Comment by Memoframe** [comment]
Seems to be wl-clip-persist issue.
I avoid it by reducing wl-clip-persist max data size to process so it's enough for text but not enough for image:
_wl-clip-persist --clipboard regular -l 4096_

**Comment by Memoframe** [comment]
was fixed in wl-clip-persist
