### ISSUE TITLE
supplied geometry did not intersect with any outputs error when trying to take a screenshot of a region

### ISSUE THREAD

**Issue by jernejmarcic** [Gustash/Hyprshot#43]
## System information
**OS:** EndeavourOS Linux x86_64 
**Kernel:** 6.8.7-arch1-1 
**DE:** Hyprland 
**CPU:** 12th Gen Intel i7-12700H (20) @ 4.600GHz 
**GPU:** Intel Alder Lake-P GT2 [Iris Xe Graphics] 
**GPU:** NVIDIA GeForce RTX 3060 Mobile / Max-Q 
**GPU Driver:** i915 

## Issue description
When trying to take a screenshot of a region with `hyprshot -m region` I get an error message:
```sh
supplied geometry did not intersect with any outputs
```
Therefore I cannot take a screenshot with it

## How to replicate
Run: `hyprshot -m region`, select an area and see what happens

**A video showing the issue:**
https://github.com/Gustash/Hyprshot/assets/91026972/43edfd4c-ebc0-48d4-8600-28a70a3248b9

**Comment by ProMix0** [comment]
Try to run it with -d option and ensure that all dependency such as grim and slurp installed

**Comment by jernejmarcic** [comment]
I have both grim and slurp installed. Hyprshot used to work and then at some point (I don't know when) it broke.
Running with debug flag:
```sh
❯ hyprshot -m region -d
Saving in: /home/jernej/Pictures/2024-04-26-090222_hyprshot.png
Geometry: 647,-595 434x227
Crop: 647,0 434x-368
supplied geometry did not intersect with any outputs
```
I assume the geometry shoudn't be negative

**Comment by ProMix0** [comment]
Do you have some monitor on negative positions?
