### ISSUE TITLE
error after update system

### ISSUE THREAD

**Issue by matv864** [Gustash/Hyprshot#49]
I update system through pacman -Suy and have this error from hyprshot

hyprshot -m region                                                                                                                                                                     11:56:13
jq: parse error: Invalid numeric literal at line 1, column 9
jq: parse error: Invalid numeric literal at line 1, column 9
supplied geometry did not intersect with any outputs

**Comment by ProMix0** [comment]
Could you run hyprshot with -d flag and post output here?

**Comment by matv864** [comment]
hyprshot -d                                                                                                                                                                                  12:23:26
A mode is required

Available modes are:
	output
	region
	window

is it?

**Comment by ProMix0** [comment]
It would be more useful:

```
hyprshot -m region 11:56:13 -d
```

**Comment by matv864** [comment]
Sorry...
the problem has disappeared.....
