### ISSUE TITLE
make an option where you dont have to click to take a screenshot

### ISSUE THREAD

**Issue by teister** [Gustash/Hyprshot#52]
currently you have to first run hyprshot, and then click to take a ss. it would be nice if there was an option like -i --instant, for the output, active, and window modes, so that when you run hyprshot -m output -i it just takes a screenshot.

**Comment by Gustash** [comment]
You can already do this. Just do `hyprshot -m window -m active` or `hyprshot-m output -m active`.

**Comment by Atemo-C** [comment]
> You can already do this. Just do `hyprshot -m window -m active` or `hyprshot-m output -m active`.

This does not work.

Here, with version `1.3.0` on NixOS, running Hyprland, the following command still requires the user to click anywhere on the screen to take a screenshot.
```shell
hyprshot \
	-m output \
	-m active \
	-o "$HOME/Images/Screenshots" \
	-f Screenshot_"$(date +'%d-%m-%Y_%H-%M-%S')".png
```
![image](https://github.com/Gustash/Hyprshot/assets/160250128/f19a306f-c340-41b7-b006-e5aa61ee7be5)

---

## Disregard
I did nothing and it now works. Literally the exact same command. Only thing I did was reinstall my system, and the version of hyprshot is exactly the same, too. I am confused, but happy that it works as intended, I guess.
