### ISSUE TITLE
freeze flag doesn't freeze screen

### ISSUE THREAD

**Issue by yorunoken** [Gustash/Hyprshot#58]
when executing `hyprshot --freeze -m output`, hyprshot doesn't freeze the screen, so stuff keeps happening

**Comment by ProMix0** [comment]
Did you install `hyprpicker`?

**Comment by yorunoken** [comment]
yeah haha that was the reason,
funny thing is I install hyprpicker and wrote a bash script that freeze the window on my own 💀 thank you

**Comment by yorunoken** [comment]
probably should add a hint in -h so people will know to download hyprpicker.
