### ISSUE TITLE
[ BUG ]: The name is not activatable

### ISSUE THREAD

**Issue by SniverDaBest** [Gustash/Hyprshot#70]
When I try and screenshot anything, it throws a `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable` error, and exits with code 1.

**Comment by Gustash** [comment]
You're probably missing a dependency. Double check you've got everything in the README installed

**Comment by ProMix0** [comment]
`mako` not started?

**Comment by GitMurf** [comment]
@SniverDaBest I had this exact same issue this week. I had just installed Arch linux recently and had Gnome desktop environment initially. But then switched to Hyprland and evidently hadn't had notification daemon installed / setup yet.

1. Try installing `swaync` - I believe this should solve the problem for you.
2. If step 1 does not solve it, then try installing: `notification-daemon` and `libnotify` ... this should do it.

Make sure to restart after installing just in case.

**Comment by SniverDaBest** [comment]
After installing `mako`, `notification-daemon`, and `libnotify` (and `libnotify-devel`) it doesn't even throw an error, but exits with error code 2.

**Comment by GitMurf** [comment]
> After installing `mako`, `notification-daemon`, and `libnotify` (and `libnotify-devel`) it doesn't even throw an error, but exits with error code 2.

Did you try `swaync`?

**Comment by SniverDaBest** [comment]
It didn't appear to be in the fedora repos... I don't really know why it wouldnt be there, it just isn't.

**Comment by ProMix0** [comment]
> After installing mako

Did you start it?

**Comment by SniverDaBest** [comment]
Fixed the issue. Just had to reinstall Hyprland.
