### ISSUE TITLE
Hyprshot not working in hyprland config

### ISSUE THREAD

**Issue by d-hain** [Gustash/Hyprshot#8]
I have a config in `~/.config/hypr/hyprland.conf` like:
`bind = SUPER SHIFT, S, exec, hyprshot -m region --clipboard-only`
and if I press `SUPER + SHIFT + S` nothing happens.

It works if I run the command in the terminal.

If it is useful in any way, I am using:
Fedora 38
hyprshot Version 1.2.1
hyprland from the solopasha/hyprland copr (notmal hyprland not nvidia or git)

**Comment by Gustash** [comment]
If you run `hyprshot -m region --clipboard-only` in your terminal, does it work?

**Comment by Gustash** [comment]
What if instead of `SUPER SHIFT` you use `SUPER_SHIFT`?

**Comment by d-hain** [comment]
Doesn't change anything ):

**Comment by solopasha** [comment]
@d-hain I packaged hyprshot in my copr, check it out... `dnf install hyprshot`. works for me with `bind = SUPER SHIFT, S, exec, hyprshot -m region --clipboard-only`

**Comment by Gustash** [comment]
> Doesn't change anything ):

The only thing I can think of is that your value of PATH is different between your terminal and Hyprland. 

Try changing the binding to execute `echo $PATH > $HOME/path.log`. Then check if `which hyprshot` returns a folder that Hyprland can see.

**Comment by d-hain** [comment]
> > Doesn't change anything ):
> 
> The only thing I can think of is that your value of PATH is different between your terminal and Hyprland.
> 
> Try changing the binding to execute `echo $PATH > $HOME/path.log`. Then check if `which hyprshot` returns a folder that Hyprland can see.

Yes that was indeed the problem, because where I put hyprshot was only put in the path in my zshrc.

**Comment by d-hain** [comment]
> @d-hain I packaged hyprshot in my copr, check it out... `dnf install hyprshot`. works for me with `bind = SUPER SHIFT, S, exec, hyprshot -m region --clipboard-only`

Thank you for also providing hyprshot now.
It is just really convenient rather than installing it manually.

That works now.
Thank you :+1:
