### ISSUE TITLE
Feature request: Specify output with command

### ISSUE THREAD

**Issue by PhlegmaTREEc** [Gustash/Hyprshot#9]
Hello, just quick question. Would it be possible to add option to specify output to take screen-shot of in the command. Like `hyprshot - m output DP-1`, so there is no need to select the output with click of a mouse.
Thanks for considering this.

**Comment by Gustash** [comment]
Yes, this is possible. I'll look into adding this as a feature

**Comment by PhlegmaTREEc** [comment]
Thank you very much for the reply

**Comment by 0xUnixy** [comment]
hello @PhlegmaTREEc 
if u want this now u do this 
![image](https://github.com/Gustash/Hyprshot/assets/137896711/698cd1cd-374c-4662-88af-c3a28bd7a21c)

in line 89.

**Comment by PhlegmaTREEc** [comment]
@0xUnixy Could you be a bit more specific, please?
Where do I put this function? Into Hyprland config?
How do I invoke it? `bind = $mainMod SHIFT, p, exec, hyprshot -m output -o ~/Pictures/Screen_Shots
` This his my current hot key. Do I add the function into it? How?

**Comment by 0xUnixy** [comment]
@PhlegmaTREEc 
First of all `hyprshot` is a bash script, and the screenshot above is the line 89 from that script.
do the following:
1. run `which hyprshot` to know where the script is located in your file system.
2. open it with your txt editor (using sudo ).
3. go to the line 89 and replace `local geometry=`grab_output` with `local geometry=0,0 1920x1080`.
4. save the file and u r good to do, there is no need to change anything in the hyprland config.

NOTE: Consider changing the resoloution to your screen resoloution.

**Comment by PhlegmaTREEc** [comment]
OK, that works, Thanks.
I do hope for actual feature, that would be more flexible on multi-monitor setup.

**Comment by Gustash** [comment]
This has been implemented in #19 

Please test it out and let me know if it's working as intended, as well as if it breaks anything.

If there are no issues in 2 weeks time I will make a new release with these changes.
